#%RAML 0.8
title: Customer Details RAML
version: 0.1

/CustomerDetails:
  displayName: CustomerDetails
  
  get:
    description: Read
    responses:
      200:
        body:
          application/json:
           
  post:
    description: Create
    body:
      application/json:
        schema: |
          {
            "$schema": "http://json-schema.org/draft-04/schema#",
            "type": "object",
            "properties": {
              "customerName" : {
                "type": "string"
              },

              "customerEmail" : {
                "type": "string"
              },

              "customerContact" : {
                "type": "string"
              },

              "customerAddress" : {
                "type": "string"
              },

              "industry" : {
                "type": "string"
              }
            },
            "required": [
              "customerName",
              "customerEmail",
              "customerContact",
              "customerAddress",
              "industry"
            ],
            "additionalProperties": false
          }
    responses:
      201:
        body:
          application/json:
            
  /{CustomerDetailsName}:
    get:
      description: Read
      responses:
        200:
          body:
            application/json:
 
